### ISSUE TITLE
Application error: a server-side exception has occurred (see the server logs for more information). Digest: 3165055376

### ISSUE THREAD

**Issue by Red-Killer** [mehdibha/palettify#13]
If I try to visit https://palettify.co/themes I get this error:
```
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3165055376
```
![image](https://github.com/mehdibha/palettify/assets/59504268/5d0f0317-06cd-4f54-87a3-34a02597bc62)
tried it on multiple clients same issue

Also I noticed the radius isnt correct if you export it someone already made a pull request about that. Also the popover color isnt changing

**Comment by mehdibha** [comment]
Fixed. there were an issue with vercel

**Comment by Red-Killer** [comment]
Whats about the Popover?
