### ISSUE TITLE
PNPM workspaces VS YARN workspace 

### ISSUE THREAD

**Issue by hitaspdotnet** [mehdibha/palettify#5]
Why you, who have relatively high experience, don't use PNPM? Should we also avoid it?

PERSONALLY:
If you are interested in building a d-app in [TON](https://ton.org) blockchain using your capabilities, [message me](https://t.me/hitasp).

**Comment by mehdibha** [comment]
Using yarn doesnt make pnpm bad. it's just a personal preference.
